#!/bin/bash

# Generated by Copilot (GPT-4), 2025-08-30
# Test script to validate auto-termination functionality

echo "Starting test script in background..."

# Clean up any existing container
if docker stop vscode-server-tunnel 2>/dev/null; then
  docker rm vscode-server-tunnel 2>/dev/null || true
fi

# Start the build script in background
./build_vscode_docker_debian_slim_secure.sh --test-mode &
SCRIPT_PID=$!

echo "Build script started with PID: $SCRIPT_PID"
echo "Waiting up to 180 seconds for auto-termination..."

# Wait for the script to complete or timeout
TIMEOUT=180
ELAPSED=0
while [ $ELAPSED -lt $TIMEOUT ]; do
  if ! kill -0 $SCRIPT_PID 2>/dev/null; then
    echo "✓ Script auto-terminated after $ELAPSED seconds"
    exit 0
  fi
  sleep 5
  ELAPSED=$((ELAPSED + 5))
  echo "  ... waiting ($ELAPSED/$TIMEOUT seconds)"
done

echo "✗ Script did not auto-terminate within $TIMEOUT seconds"
echo "Killing script with PID: $SCRIPT_PID"
kill -TERM $SCRIPT_PID 2>/dev/null || true
sleep 2
kill -KILL $SCRIPT_PID 2>/dev/null || true
exit 1
