#!/usr/bin/env bash

# Generated by Copilot (GPT-4) on 2025-08-29
# Script to build and package the VS Code Container Updater extension
# This creates a .vsix file that can be installed in VS Code

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXTENSION_DIR="$SCRIPT_DIR/../vscode-container-updater"

cd "$EXTENSION_DIR"

echo "Building VS Code Container Updater extension..."

# Install dependencies
echo "Installing npm dependencies..."
npm install

# Compile TypeScript
echo "Compiling TypeScript..."
npm run compile

# Install vsce if not available
if ! command -v vsce >/dev/null 2>&1 && ! npx @vscode/vsce --version >/dev/null 2>&1; then
    echo "Installing @vscode/vsce locally..."
    npm install @vscode/vsce
fi

# Package extension
echo "Packaging extension..."
if command -v vsce >/dev/null 2>&1; then
    vsce package --out vscode-container-updater.vsix
else
    npx @vscode/vsce package --out vscode-container-updater.vsix
fi

echo "Extension packaged successfully: vscode-container-updater.vsix"
echo "To install: code --install-extension vscode-container-updater.vsix"
